ci: ha

diff --git a/.github/workflows/ci-ha.yml b/.github/workflows/ci-ha.yml
--- a/.github/workflows/ci-ha.yml
+++ b/.github/workflows/ci-ha.yml
@@ -33,13 +33,16 @@ jobs:
       shell: bash
       run: |
           echo "test access to phpldapadmin"
-          echo "127.0.0.1 phpldapadmin.example ssl-ldap2.example" | sudo tee -a /etc/hosts
-          curl phpldapadmin.example:8080
+          IP=$(kubectl -n ha get svc openldap-phpldapadmin  -o jsonpath='{.spec.clusterIP}')
+          echo "LDAP Admin portal IP: $IP"
+          curl "$IP":80 | grep 'meta name="description"'
     - name: test self service pwd access
       shell: bash
       run: |
           echo "test access to ssp"
-          curl ssl-ldap2.example:8080
+          IP=$(kubectl -n ha get svc openldap-ltb-passwd -o jsonpath='{.spec.clusterIP}')
+          echo "Self Service Password portal IP: $IP"
+          curl "$IP":80 | grep 'div id="footer"'
     - name: verify certs
       shell: bash
       run: |
@@ -59,24 +62,25 @@ jobs:
       shell: bash
       run: |
           echo "test access to openldap database"
-          kubectl -n ha apply -f .bin/chaos.yaml
+          kubectl -n ha apply -f .bin/ha-chaos.yaml
     - name: test write
       shell: bash
       run: |
           echo "Write test to openldap database"
-          LDAPTLS_REQCERT=never ldapadd -x -D 'cn=admin,dc=example,dc=org' -w Not@SecurePassw0rd -H ldaps://localhost:30636 -f .bin/user.ldif
+          LDAPTLS_REQCERT=never ldapadd -x -D 'cn=admin,dc=example,dc=org' -w Not@SecurePassw0rd -H ldaps://localhost:30636 -f .bin/ha-write.ldif
           LDAPTLS_REQCERT=never ldapsearch -o nettimeout=20 -x -D 'cn=admin,dc=example,dc=org' -w Not@SecurePassw0rd -H ldaps://localhost:30636 -b 'dc=example,dc=org' > /tmp/test-write.txt
           if ! grep  "Einstein" /tmp/test-write.txt; then echo 'no Einstein entry found' ; fi
-          if ! grep  "objectClass: ownCloud" /tmp/test-write.txt; then  echo 'no ownCloud entry found'; fi
+          if [ $(grep -c "objectClass: ownCloud" /tmp/test-write.txt) -ne 2 ]; then echo 'expected two ownCloud entries'; fi
     - name: test memberOf
       shell: bash
       run: |
           echo "MemberOf test to openldap database"
-          LDAPTLS_REQCERT=never ldapsearch -o nettimeout=20 -x -D 'cn=admin,dc=example,dc=org' -w Not@SecurePassw0rd -H ldaps://localhost:30636 -b 'dc=example,dc=org' "(memberOf=cn=testgroup,ou=Group,dc=example,dc=org)" > /tmp/test-write.txt
-          if [ $(grep "numResponses" /tmp/test-write.txt | cut -d ":" -f 2 | tr -d ' ') -ne 2 ]; then exit 1 ; fi
-          if ! grep -q "uid=test1,ou=People,dc=example,dc=org" /tmp/test-write.txt; then  echo exit 1; fi
+          LDAPTLS_REQCERT=never ldapsearch -o nettimeout=20 -x -D 'cn=admin,dc=example,dc=org' -w Not@SecurePassw0rd -H ldaps://localhost:30636 -b 'dc=example,dc=org' "(memberOf=cn=mygroup,dc=example,dc=org)" > /tmp/test-memberof.txt
+          if [ $(grep "numResponses" /tmp/test-memberof.txt | cut -d ":" -f 2 | tr -d ' ') -ne 3 ]; then echo 'expected 1+2 responses' ; exit 1 ; fi
+          if ! grep -q "uid=jdupond,dc=example,dc=org" /tmp/test-memberof.txt; then  echo 'expected initial member not found' ; exit 1; fi
+          if ! grep -q "uid=einstein,dc=example,dc=org" /tmp/test-memberof.txt; then  echo 'expected written member not found' ; exit 1; fi
     - name: chaos tests
       shell: bash
       run: |
           echo "test access to openldap database"
-          for i in {1..20}; do  LDAPTLS_REQCERT=never ldapsearch -o nettimeout=20 -x -D 'cn=admin,dc=example,dc=org' -w Not@SecurePassw0rd -H ldaps://localhost:30636 -b 'dc=example,dc=org' && sleep 60 ; done
+          for i in {1..20}; do  LDAPTLS_REQCERT=never ldapsearch -o nettimeout=20 -x -D 'cn=admin,dc=example,dc=org' -w Not@SecurePassw0rd -H ldaps://localhost:30636 -b 'dc=example,dc=org' && sleep 20 ; done
